[package]
name = "c509"
version = "0.1.0"
authors = ["Oleksandr Kravchenko <zartarn15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
serde_cbor = "0.11.1"
